name: TAGTAGTAG
favicon: null
layout_spectrum: 0.7808480144012719
typography_spectrum: 0.6429634550586343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a2adb3'
    - '#3c4648'
    - '#d73cac'
    - '#5df5ec'
  brandStrength: 0.7763089565560222
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
